"""empty message

Revision ID: 0605540dd089
Revises: ff30d0f83192
Create Date: 2024-10-26 19:08:31.452355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0605540dd089'
down_revision = 'ff30d0f83192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_information',
    sa.Column('region', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('population_male', sa.Integer(), nullable=False),
    sa.Column('population_female', sa.Integer(), nullable=False),
    sa.Column('n_households', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region_information')
    # ### end Alembic commands ###
