"""empty message

Revision ID: 2c4e9c91b150
Revises: d4af9ef7b61b
Create Date: 2024-11-12 11:59:28.755482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4e9c91b150'
down_revision = 'd4af9ef7b61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.alter_column('type_flour',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.alter_column('type_flour',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
