"""empty message

Revision ID: 6753e8a78a15
Revises: 83c270de74ad
Create Date: 2024-11-15 20:07:33.668963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6753e8a78a15'
down_revision = '83c270de74ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flour_types', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('bread_types', sa.String(length=30), nullable=True))
        batch_op.drop_column('type_flour')
        batch_op.drop_column('type_bread')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_bread', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('type_flour', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('bread_types')
        batch_op.drop_column('flour_types')

    # ### end Alembic commands ###
