"""empty message

Revision ID: 83c270de74ad
Revises: 
Create Date: 2024-11-15 17:07:07.412173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c270de74ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amarnameh',
    sa.Column('ostan', sa.String(length=30), nullable=False),
    sa.Column('shahrestan', sa.String(length=30), nullable=False),
    sa.Column('bakhsh', sa.String(length=30), nullable=False),
    sa.Column('shahr', sa.String(length=30), nullable=False),
    sa.Column('region', sa.Integer(), nullable=False),
    sa.Column('district', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('population_male', sa.Integer(), nullable=False),
    sa.Column('population_female', sa.Integer(), nullable=False),
    sa.Column('n_households', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bakers_risk',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bakery',
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('nid', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('bakery_id', sa.String(length=30), nullable=True),
    sa.Column('ownership_status', sa.String(length=30), nullable=True),
    sa.Column('number_violations', sa.Integer(), nullable=True),
    sa.Column('second_fuel', sa.String(length=30), nullable=True),
    sa.Column('ostan', sa.String(length=30), nullable=True),
    sa.Column('shahrestan', sa.String(length=30), nullable=True),
    sa.Column('bakhsh', sa.String(length=30), nullable=True),
    sa.Column('shahr', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('household_risk', sa.String(length=30), nullable=True),
    sa.Column('bakers_risk', sa.String(length=30), nullable=True),
    sa.Column('type_flour', sa.String(length=30), nullable=True),
    sa.Column('type_bread', sa.String(length=30), nullable=True),
    sa.Column('bread_rations', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_risk',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ownership_status',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('second_fuel',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('type_bread',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('type_flour',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('type_flour')
    op.drop_table('type_bread')
    op.drop_table('second_fuel')
    op.drop_table('ownership_status')
    op.drop_table('household_risk')
    op.drop_table('bakery')
    op.drop_table('bakers_risk')
    op.drop_table('amarnameh')
    # ### end Alembic commands ###
