"""empty message

Revision ID: 8c908405534a
Revises: f58928a411f9
Create Date: 2024-11-12 13:06:54.222735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c908405534a'
down_revision = 'f58928a411f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.alter_column('bread_rations',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.alter_column('bread_rations',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
