"""empty message

Revision ID: f18f4815f0d4
Revises: 8c908405534a
Create Date: 2024-11-12 17:20:00.745081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18f4815f0d4'
down_revision = '8c908405534a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ostan', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('shahrestan', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('bakhsh', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('shahr_rosta', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.drop_column('shahr_rosta')
        batch_op.drop_column('bakhsh')
        batch_op.drop_column('shahrestan')
        batch_op.drop_column('ostan')

    # ### end Alembic commands ###
