"""empty message

Revision ID: f307dd668335
Revises: f18f4815f0d4
Create Date: 2024-11-12 20:46:17.760598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f307dd668335'
down_revision = 'f18f4815f0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shahr', sa.String(length=30), nullable=True))
        batch_op.drop_column('shahr_rosta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shahr_rosta', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('shahr')

    # ### end Alembic commands ###
