"""empty message

Revision ID: f58928a411f9
Revises: 2c4e9c91b150
Create Date: 2024-11-12 13:04:55.028509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58928a411f9'
down_revision = '2c4e9c91b150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.alter_column('bread_rations',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakery', schema=None) as batch_op:
        batch_op.alter_column('bread_rations',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
